CREATE TABLE USER (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  first_name VARCHAR(30),
  last_name  VARCHAR(50),
  login      VARCHAR(20),
  oldPassword   VARCHAR(60),

  PRIMARY KEY(id)
);

CREATE TABLE TASK (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  task_name VARCHAR(30),
  done      BOOLEAN,
  user_id   INTEGER,

  FOREIGN KEY(user_id) REFERENCES USER(id)
);


--INSERT INTO USER (first_name,last_name,login,oldPassword) VALUES ('John', 'Rambo','JohnDeath','t454@$#$!@RCF@!E@EX');
--INSERT INTO USER (first_name,last_name,login,oldPassword) VALUES ('Johny','Bravo','Bravo007','f4@%@$QTQC42t34tfaadx');